### ISSUE TITLE
Problème avec Sox

### ISSUE THREAD

**Issue by Oliviercreativ** [jystervinou/freebox-caller-id#11]
Bonjour, 
Je viens d'installer freebox called id ! L'installation c'est bien passé aucunes erreurs.
Je lance dans mon terminal : node caller_id.js,il se lance normalement,
Par contre dès j'ai un appel je reçois mon sms mais j'ai une erreur qui fait planter le script.

Voici  l'erreur : 
``info: Sending notifications... {}
info: Sending 1 SMS... {}
error: /usr/bin/sox WARN dither: dither clipped 45 samples; decrease volume?
/usr/bin/sox WARN sox: `./voice.wav' balancing clipped 50 samples; decrease volume?
 {}
info: Sending voice... {}
info: SMS sent {}
info: All SMS sent {}
info: All notifications sent {}
info: status: ready {}
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at AirTunesDevice.<anonymous> (/home/pi/github/freebox-caller-id/caller_id.js:417:16)
    at emitOne (events.js:121:20)
    at AirTunesDevice.emit (events.js:211:7)
    at AirTunesDevice.relayAudio (/home/pi/github/freebox-caller-id/node_modules/airtunes/lib/device_airtunes.js:80:8)
    at Client.<anonymous> (/home/pi/github/freebox-caller-id/node_modules/airtunes/lib/device_airtunes.js:64:10)
    at emitNone (events.js:106:13)
    at Client.emit (events.js:208:7)``

Version node  : v8.9.0
Version NPM : 5.5.1
Raspberry pi zero W

Si quelqu'un peut m'aider s'il vous plaît ;)

**Comment by Oliviercreativ** [comment]
Désolé je viens de corriger mon problème ! 
En faites, j'ai mal copié les fichier ffmpeg. 
Je suis rentrer dans le dossier ffmpeg-3.4.1-armel-32bit-static/ et j'ai copié comme ceci : 
`sudo cp -Rf ff* /usr/local/bin/` et maintenant tout marche ;)

**Comment by jystervinou** [comment]
cool ;-)

**Comment by Oliviercreativ** [comment]
Par contre, je me demandais si ce n'était pas intéressant de le fusionner avec le contrôle de la Freebox avec le Google Home ?
https://github.com/Aymkdn/assistant-plugins

**Comment by jystervinou** [comment]
Pour faire quoi par exemple ? (Bonjour :-)) )

**Comment by Oliviercreativ** [comment]
Parler à sa freebox et entendre l'appel entrant ! Soit sur le serveur soit sur le google home. Et on a qu'un script node à faire tourner en arrière plan au lieu de 2 !

**Comment by jystervinou** [comment]
ok, je te laisse créer une nouvelle issue avec le label "feature request" :) 

Fusionner n'aurait pas trop de sens (genre t'as pas de Google Home comme moi) car ils sont complémentaires, mais voir comment les intégrer éventuellement.

Merci

**Comment by Oliviercreativ** [comment]
je test et je reviens vers toi !

Bonne soirée ;)
