### ISSUE TITLE
Problème d'Installation (airtunes)

### ISSUE THREAD

**Issue by TitouBilou** [jystervinou/freebox-caller-id#16]
Bonjour Jean-Yves,

J'ai un petit problème à l'installation. Tout d'abord j'ai changé :
$ wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-armhf-32bit-static.tar.xz
$ tar -xJf ffmpeg-release-armhf-32bit-static.tar.xz
$ sudo cp ffmpeg-3.4-armhf-32bit-static/ff* /usr/local/bin/

Par :
$ wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-armhf-static.tar.xz
$ tar -xJf ffmpeg-release-armhf-static.tar.xz
$ sudo cp ffmpeg-4.1.4-armhf-static/ff* /usr/local/bin/

Car la version de ffmpeg n'est plus disponible à l'adresse indiquée.

J'ai bien renseigné mon login et password Free pour l'envoi de SMS dans le fichier local.json créé à partir de default.json. Ensuite tout se passe correctement jusqu'à :
$ node caller_id.js init

Où j'obtiens :
internal/modules/cjs/loader.js:628
    throw err;
    ^
Error: Cannot find module 'airtunes'
Require stack:
- /home/pi/freebox-caller-id/caller_id.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/freebox-caller-id/caller_id.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/freebox-caller-id/caller_id.js' ]

Les infos sur mon système:
- RPi3B
- Distribution : Raspbian Buster
- Linux version 4.19.60-v7+
- node : v12.7.0

Par avance, merci pour ton aide.
Eric.

**Comment by jystervinou** [comment]
Hello,

Il semble qu'il manque le `npm install` car le module airtunes n'est pas installé.

JY

**Comment by TitouBilou** [comment]
Merci pour ta réponse expresse !!!!
Voici le retour de la commande "npm install" :
$ pi@RaspNews:~/freebox-caller-id $ npm install

> airtunes@0.1.7 install /home/pi/freebox-caller-id/node_modules/airtunes
> node-gyp rebuild

make : on entre dans le répertoire « /home/pi/freebox-caller-id/node_modules/airtunes/build »
  CXX(target) Release/obj.target/airtunes/src/codec.o
In file included from ../src/../alac/ALACEncoder.h:29,
                 from ../src/codec.cc:15:
../src/../alac/ALACAudioTypes.h:64:32: warning: multi-character character constant [-Wmultichar]
     kALACFormatAppleLossless = 'alac',
                                ^~~~~~
../src/../alac/ALACAudioTypes.h:65:28: warning: multi-character character constant [-Wmultichar]
     kALACFormatLinearPCM = 'lpcm'
                            ^~~~~~
../src/../alac/ALACAudioTypes.h:154:22: warning: multi-character character constant [-Wmultichar]
  kALACCodecFormat  = 'alac',
                      ^~~~~~
../src/../alac/ALACAudioTypes.h:182:26: warning: multi-character character constant [-Wmultichar]
  AudioChannelLayoutAID = 'chan'
                          ^~~~~~
../src/codec.cc: In function ‘void nodeairtunes::NewEncoder(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/codec.cc:76:49: error: no matching function for call to ‘v8::ObjectTemplate::NewInstance()’
   Local<Object> obj = encoderClass->NewInstance();
                                                 ^
In file included from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:6252:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::ObjectTemplate::NewInstance(v8::Local<v8::Context>)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(Local<Context> context);
                                            ^~~~~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:6252:44: note:   candidate expects 1 argument, 0 provided
../src/codec.cc: In function ‘void nodeairtunes::EncodeALAC(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/codec.cc:91:44: error: no matching function for call to ‘v8::Value::ToObject()’
   Local<Object>wrapper = args[0]->ToObject();
                                            ^
In file included from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2539:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2539:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/pi/.node-gyp/12.7.0/include/node/v8-internal.h:14,
                 from /home/pi/.node-gyp/12.7.0/include/node/v8.h:25,
                 from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2553:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2553:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/codec.cc:95:77: error: no matching function for call to ‘v8::Value::ToObject()’
   unsigned char* pcmData = (unsigned char*)Buffer::Data(pcmBuffer->ToObject());
                                                                             ^
In file included from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2539:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2539:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/pi/.node-gyp/12.7.0/include/node/v8-internal.h:14,
                 from /home/pi/.node-gyp/12.7.0/include/node/v8.h:25,
                 from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2553:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2553:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/codec.cc:98:79: error: no matching function for call to ‘v8::Value::ToObject()’
   unsigned char* alacData = (unsigned char*)Buffer::Data(alacBuffer->ToObject());
                                                                               ^
In file included from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2539:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2539:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/pi/.node-gyp/12.7.0/include/node/v8-internal.h:14,
                 from /home/pi/.node-gyp/12.7.0/include/node/v8.h:25,
                 from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2553:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2553:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/codec.cc:100:41: error: no matching function for call to ‘v8::Value::Int32Value()’
   int32_t pcmSize = args[3]->Int32Value();
                                         ^
In file included from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2576:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2576:40: note:   candidate expects 1 argument, 0 provided
../src/codec.cc: In function ‘void nodeairtunes::EncryptAES(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/codec.cc:122:79: error: no matching function for call to ‘v8::Value::ToObject()’
   unsigned char* alacData = (unsigned char*)Buffer::Data(alacBuffer->ToObject());
                                                                               ^
In file included from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2539:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2539:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/pi/.node-gyp/12.7.0/include/node/v8-internal.h:14,
                 from /home/pi/.node-gyp/12.7.0/include/node/v8.h:25,
                 from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2553:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2553:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/codec.cc:123:42: error: no matching function for call to ‘v8::Value::Int32Value()’
   int32_t alacSize = args[1]->Int32Value();
                                          ^
In file included from /home/pi/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../src/codec.cc:1:
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2576:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.node-gyp/12.7.0/include/node/v8.h:2576:40: note:   candidate expects 1 argument, 0 provided
../src/codec.cc: At global scope:
../src/codec.cc:149:16: error: variable or field ‘InitCodec’ declared void
 void InitCodec(Handle<Object> target) {
                ^~~~~~
../src/codec.cc:149:16: error: ‘Handle’ was not declared in this scope
../src/codec.cc:149:16: note: suggested alternative: ‘rand_r’
 void InitCodec(Handle<Object> target) {
                ^~~~~~
                rand_r
../src/codec.cc:149:29: error: expected primary-expression before ‘>’ token
 void InitCodec(Handle<Object> target) {
                             ^
../src/codec.cc:149:31: error: ‘target’ was not declared in this scope
 void InitCodec(Handle<Object> target) {
                               ^~~~~~
../src/codec.cc:149:31: note: suggested alternative: ‘tzset’
 void InitCodec(Handle<Object> target) {
                               ^~~~~~
                               tzset
make: *** [airtunes.target.mk:113: Release/obj.target/airtunes/src/codec.o] Error 1
make : on quitte le répertoire « /home/pi/freebox-caller-id/node_modules/airtunes/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:266:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.60-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/freebox-caller-id/node_modules/airtunes
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN freebox-caller-id@0.8.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! airtunes@0.1.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the airtunes@0.1.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-07-30T22_49_39_856Z-debug.log

********  FIN ***********
Rien n'a ensuite changé pour la réponse à la commande : "node caller_id.js init".

Par avance, merci.
Eric.

**Comment by jystervinou** [comment]
C'est la fête toutes ces erreurs et warnings :-)

Peux-tu tenter :  

```
cd /home/pi/freebox-caller-id/node_modules/airtunes
node-gyp configure build

```

**Comment by TitouBilou** [comment]
Pas de modules airtunes dans /home/pi/freebox-caller-id/node_modules/
$ cd /home/pi/freebox-caller-id/node_modules/airtunes
bash: cd: /home/pi/freebox-caller-id/node_modules/airtunes: Aucun fichier ou dossier de ce type

Je te joins le log de "npm install" si cela peut aider...

[freebox-caller-id_debug.log](https://github.com/jystervinou/freebox-caller-id/files/3449161/freebox-caller-id_debug.log)


Encore merci,
Eric.

**Comment by jystervinou** [comment]
Ca sent le #fail avec la version la plus récente de Node. :-/ 

Peux-tu quand même essayer un :  

```
cd /home/pi/freebox-caller-id/
npm install jystervinou/node_airtunes
```

Sinon, est-ce que tu as installé node ou était-il déjà installé ?

Faudrait essayer d'installer une vielle version, genre j'étais en v8.9.1 ...
possible d'en installer plusieurs avec [nvm](https://github.com/nvm-sh/nvm)  mais c'est tout de suite un peu plus relou..

**Comment by TitouBilou** [comment]
Malheureusement pas plus de succès...
Node était déjà installé, je pense que je vais effectivement devoir installer une version un peu plus ancienne...

Merci pour ton aide,
Eric.

**Comment by TitouBilou** [comment]
Eh oui, c'était probablement du à la version de node car cela fonctionne parfaitement avec en v8.16.0.

Merci pour ton aide précieuse, je clos le sujet.
Eric.

**Comment by jystervinou** [comment]
Top, merci pour le retour.

Du coup, je ne sais pas si ça va être dur ou pas de mettre à niveau le module airtunes pour Node v12... :-/

**Comment by jystervinou** [comment]
As-tu essayé avec la dernière v10 ?

**Comment by TitouBilou** [comment]
Non, j'avais juste à disposition un autre RPi avec node v8.16.0 installé.

Eric.

**Comment by Ablis78** [comment]
Bonjour Jean-Yves,
pour information:
j'ai installé freebox-caller-id sur une VM - debian 10 sur la freebox Delta. Avec les versions de node.js 8.16.0 et 10.24.1 ça fonctionne le seul message gênant concerne la license ( npm WARN freebox-caller-id@0.8.0 license should be a valid SPDX license expression ) ceci peut être corrigé en modifiant le fichier package.json en remplaçant "license": "GPL" par "license": "(ISC OR GPL-3.0)"

Voici les versions testées. Les versions 12 et 16 tombent en erreur lors de la compilation d'airtunes
node/8.16.0
ο node/10.24.1
node/12.16.2
node/12.22.7
node/16.13.1
Merci en tout cas pour cet utilitaire qui évite souvent de décrocher pour se rendre compte que c'est encore un appel publicitaire...

**Comment by jystervinou** [comment]
@Ablis78 salut. j'ai mis : 

`"license": "MIT"`

ok ?

**Comment by jystervinou** [comment]
@Ablis78 j'avais regardé rapidement, la mise à jour éventuelle du module airtunes pour ces versions de node avait l'air gore...  :-/

**Comment by Ablis78** [comment]
Merci Jean Yves pour la rapidité de réponse et l’excellent suivi de ce projet.
