### ISSUE TITLE
L'appli ne fonctionne pas

### ISSUE THREAD

**Issue by TitouBilou** [jystervinou/freebox-caller-id#18]
Bonjour,
J'ai installé l'appli sans aucun problème, toutefois elle ne fonctionne pas (j'ai également testé le service SMSapi de Free qui est fonctionnel). Je soupçonne une incompatibilité dans ma configuration qui est la suivante :
- Raspberry Pi 3 Model B Rev 1.2 
- Raspbian Buster
- packages installés : ffmpeg-4.2.2, libttspico0_1.0+git20130326-9_armhf.deb, libttspico-data_1.0+git20130326-9_all.deb, libttspico-utils_1.0+git20130326-9_armhf.deb et svox_1.0+git20130326-9.debian
- Node.js v13.13.0
- npm 6.14.4
Une idée sur la source du problème ?
Par avance, merci.
Eric.

**Comment by jystervinou** [comment]
Salut,

Je viens d'installer une Raspbian Buster (sur mon Raspberry Pi 3 Model B Rev 1.2), je vais essayer de voir ce qui coince.

Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l

A+

**Comment by jystervinou** [comment]
Bon, tout semble OK sauf la partie audio....

Vu le nombre de warnings à l'installation de node airtunes, je pense que le soucis vient de là...

Je creuse..

**Comment by jystervinou** [comment]
Après quelques heures dessus, je pense que j'ai réussi à le faire fonctionner.. A suivre..

**Comment by TitouBilou** [comment]
Salut,

Voilà ma version sur le RasPi :
Linux version 4.19.114-v7+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1303 SMP Tue Apr 7 15:44:16 BST 2020
J'ai constaté effectivement les erreurs multiples à l'installation de airtunes. Par contre le signalement par SMS ne fonctionne pas non plus, pourtant l'api SMS de free fonctionne bien avec mes identifiants.

A Plus,
Eric.

**Comment by jystervinou** [comment]
Salut,

Je suis toujours dessus. SMS ok et voix ok, mais ça drop des frames de l'audio, et je comprends pas pourquoi, j'essaye de comprendre ce qui a bien pu changer.

**Comment by jystervinou** [comment]
les warnings à l'installation de airtunes n'ont pas l'air d'être problématiques en fait.

**Comment by TitouBilou** [comment]
Merci pour ton implication. N'hésite pas si je peux t'être utile (faire des tests ou autre).

A Plus,
Eric.

**Comment by jystervinou** [comment]
Hello,

J'ai commité un fix dans le fork github:jystervinou/node_airtunes

Est-ce que tu peux récupérer la modif et retester avec ça STP ?

Merci.

(J'ai toujours à régler le problème de son qui hache..)

**Comment by jystervinou** [comment]
Pour info j'ai gardé la version par défaut de node fournie avec Buster

node --version
v10.15.2

**Comment by jystervinou** [comment]
Pour les SMS, moi ça fonctionne, est-ce que ce serait à cause du module "request" qui est deprecated. Qui fonctionnerait encore avec la 10.15.2, et non avec la 13.13.0 ??

**Comment by jystervinou** [comment]
Cette ligne où "request" est utilisé, faut que je change ça donc :

https://github.com/jystervinou/freebox-caller-id/blob/master/caller_id.js#L307

**Comment by TitouBilou** [comment]
Bonjour,

Je viens de cloner node_airtunes dans /freebox-caller-id puis "nm install airtunes". J'ai eu plein d'erreurs à l'installation, puis plus aucun dossier "airtunes" dans "node_modules"...
J'ai constaté que dans "/freebox-caller-id/node_modules" j'avais un dossier "node-freeboxos"... C'est normal ?

Merci,
Eric.

**Comment by jystervinou** [comment]
_npm update_ dans le répertoire principal freebox-caller-id/ ? Ca devrait mettre à jour tout seul le module node_airtunes.

Oui node-freeboxos est utilisé pour dialoguer avec Freebox OS sur le Freebox Server. (et s'authentifier auprès de lui)

**Comment by TitouBilou** [comment]
Je viens de faire _npm install_ dans le répertoire de _freebox-caller-caller-id_, il y a eu de nombreuses erreurs. Je joins le retour de la commande dans le fichier attaché.
[npm_install.txt](https://github.com/jystervinou/freebox-caller-id/files/4498858/npm_install.txt)

**Comment by TitouBilou** [comment]
Désolé j'ai fait _npm install_ dans _freebox-caller-id_ (1 seule fois "caller"...)     ;-)

**Comment by jystervinou** [comment]
Bizarre, node_airtunes qui compile pas. J'ai eu des warnings mais pas des erreurs.

C'est avec un _git clone_ frais dans un autre répertoire ?

**Comment by jystervinou** [comment]
As-tu possibilité de tester avec une autre version de node, en installant _nvm_, ou _n_ (que je ne connais pas) par exemple ?

**Comment by jystervinou** [comment]
il est possible que des choses dans V8 qui étaient encore deprecated dans node 10.15.2 aient été complètement virés dans une v13.

??

**Comment by TitouBilou** [comment]
Merci pour les pistes. Je teste tout ça et je reviens vers toi.

Eric.

**Comment by TitouBilou** [comment]
Bonsoir,
Bon après être reparti de scratch et avoir installé node en version 10.15.2, quand dans le répertoire _freebox-caller-id_ je lance _node caller_id.js_ (après l'avoir initialisé sur la Freebox naturellement) à la fois l'envoi SMS et l'audio fonctionnent (peut être effectivement quelques frames audio perdues en route...). Donc tout semble Ok . PAR CONTRE si j'ajoute la ligne _node /home/pi/freebox-caller-id/caller_id.js &_ dans le fichier _/etc/rc.local_ (avant exit 0) pour lancer le script au démarrage du Raspberry Pi, quand je reboote... Plus de SMS, plus d'audio ! Curieux, non ?
Pour info j'ai deux autres scripts qui se lancent au reboot du Raspberry Pi sans problème (_zram.sh &_ pour un swap de mémoire et un bot meteo _meteo.js &_).
Merci en tous cas pour tes efforts qui sont déjà fructueux !
Eric.

**Comment by jystervinou** [comment]
Cool. Ca progresse :->

Par contre corriger node_airtunes pour qu'il compile avec les versions plus récentes de v8 ça va pas être de la tarte.

Je n'ai jamais essayé de le démarrer au boot, et j'ai souvenir qu'un autre n'avait pas réussi, tu peux fouiller dans les autres messages ? Faut que j'essaye aussi.

A+

**Comment by jystervinou** [comment]
Pour info le script utilise la méthode _pas fine_ pour interroger l'API du Freebox Server : un appel toutes les secondes ou une durée dans ce genre là. Car il n'y a pour le moment aucun moyen d'être notifié lorsqu'un appel a lieu.

**Comment by TitouBilou** [comment]
Par rapport à mon message précédent je viens de m'apercevoir que mon autre script Node ne se lançait pas non plus. J'ai vérifié le chemin de Node, il est bien dans _$PATH_ (Node a été installé par nvm et le chemin est automatiquement ajouté à _$PATH_). Le problème vient donc de Node... (le script bash est Ok).
Je n'avais aucun problème à lancer caller_id.js au boot lorsque le Raspberry Pi était sous Jessie, cela fonctionnait sans problème.

**Comment by TitouBilou** [comment]
Ça y est, je vais enfin pouvoir clore le sujet grâce à ton aide !
Pour lancer le script _caller_id.js_ au démarrage du Raspberry Pi (comme cela ne fonctionne pas dans le fichier _rc.local_), il suffit d'utiliser le fichier _crontab_ en rajoutant cette ligne :
_@ reboot /chemin/d'acces vers/node /chemin/d'acces vers/caller_id.js &_
C'est tout !
Merci encore pour ton aide plus que précieuse,
Eric.
