### ISSUE TITLE
Ajouter un message avant le numéro

### ISSUE THREAD

**Issue by alexisrgd** [jystervinou/freebox-caller-id#2]
Pour ceux qui souhaitent rajouter un message avant le numéro :  

Editer config.json : 
` {
  "login" : "12345678",
  "pass" : "xxxxxxxxxxxxxx"
 }`

Remplacer par : 
`{
  "login" : "12345678",
  "pass" : "xxxxxxxxxxxxxx",
  "msg" : "FreeboxCallerId : appel en cours du numero "
}`

Puis éditer caller_id.js (ligne 77) : 
`request({uri: smsAPI + 'user=' + user.login + '&pass=' + user.pass + '&msg=' + call.number}, function(error, response, body) {`

Remplacer par : 
`request({uri: smsAPI + 'user=' + user.login + '&pass=' + user.pass + '&msg=' + user.msg + call.number}, function(error, response, body) {`

**Comment by flimo44** [comment]
Merci.
Il ne manque plus que le nom de la personne qui appelle. 

caller_id.js (ligne 77) :

  request({uri: smsAPI + 'user=' + user.login + '&pass=' + user.pass + '&msg=' + "Appel :" + call.name + "\n\r Numéro : " + call.number}, function(error, response, body) {

**Comment by jystervinou** [comment]
En fait, j'avais rien mis devant le numéro, pour être sûr de voir le numéro dans la notification de réception du SMS, sur l'écran verrouillé de Android.

Malgré ce texte rajouté, vous voyez toujours le numéro sans avoir à faire une seule manipulation sur le téléphone ?

**Comment by flimo44** [comment]
Effectivement je vois le nom uniquement. A voir à l'usage. Mais un simple appui sur la notification  ouvre le message et me permet de tout voir donc.

Tous mes contacts sont enregistrés. Donc je préfère pour le moment ne voir que le nom.

J'attends d'avoir des appels inconnus pour voir ce que ça donne.

Maintenant libre à chacun d'adapter avec les exemples de code ci-dessus.

**Comment by jystervinou** [comment]
et si je me lache, je peux même mettre un template ;-))

**Comment by alexisrgd** [comment]
Allé un beau template :)

**Comment by jystervinou** [comment]
C'est fait, Templates dispos dans la version 0.5.0.
Merci de me dire si ça marche ;-)

**Comment by Marimax01** [comment]
Bonsoir je viens d'installer votre projet chez moi. Tout d'abord je vous remercie @jystervinou  c'est un super boulot, simple d'installation et simple d'd'utilisation que demander de mieux. 
Cependant, j'aimerai avoir plus de détail pour le template par défaut. Le nom associé au numero doit être enregistré sur le téléphone fixe ou sur le truc des contacts de la freebox ?

**Comment by jystervinou** [comment]
De rien.

Ce doit être le nom stocké dans les contacts de la Freebox. (je dis "doit être" car je n'ai jamais de nom affiché, que le numéro :-)) ) -- une chose est sûre, ce n'est pas le nom enregistré dans le téléphone fixe.

D'ailleurs, ça me fait penser à ça, je me rends compte que je n'ai jamais l'affichage du nom de l'appelant (comme sur une ligne fixe Orange par exemple). Quelqu'un sait si c'est censé fonctionner ça ?

**Comment by jystervinou** [comment]
@Marimax01  Cf #3 que je viens de créer.

**Comment by jystervinou** [comment]
J'ai mis à jour la doc avec des liens vers la syntaxe du moteur de templates doT, et la liste des champs disponibles pour 'call'.
