### ISSUE TITLE
Durée de l autorisation

### ISSUE THREAD

**Issue by keerigan** [jystervinou/freebox-caller-id#4]
Bonjour, j ai installé  le script sur mon pi3 mais j ai l'impression que l'autorisation de l'appli de dire que 24h.
Ça fonctionne très bien puis le lendemain plus rien. Il y a qqchose à changer pour que l autorisation soit permanente ?

**Comment by jystervinou** [comment]
Bonjour,

Que se passe-t-il exactement au bout de 24h ? une erreur du script ? 

Je viens de faire un appel sur mon install, sur un pi3 installé samedi, et j'ai bien reçu le SMS.

**Comment by keerigan** [comment]
oui effectivement une erreur d'authentification
je relance le script et je post l'erreur demain :)

**Comment by jystervinou** [comment]
en fait ce ne doit pas être une "vraie" erreur.

plus précisément, c'est une erreur comme quoi le token de session n'est plus valable, mais dans ce cas-là la librairie node-freeboxos redemande automatiquement un token..

je crois que c'est la librairie node-freeboxos qui affiche ça et non mon script, il faut que je regarde

(je ne sais plus combien de temps sont valables les token de freebox OS, je pensais que c'était même plus court que 24h, mais ça se trouve c'est bien 24h)

**Comment by jystervinou** [comment]
mmm non c'est bien moi qui affiche l'erreur de token expiré. je vais changer ça.

**Comment by keerigan** [comment]
j'ai dis 24h mais ça peut être moins :) je n'ai pas tant d'appel par jour lol :)
Merci pour tes réponses, et pour ta réactivité :+1:

**Comment by keerigan** [comment]
Beh après plus de 24h , ça tient le coup ....Je ne comprends pas pourquoi j'ai eu des déconnexions plusieurs fois les jours d'avant. 
Je continue de surveiller...

**Comment by jystervinou** [comment]
La déconnexion est normale. Les token générés par la box expirent.

Maintenant quand le token expire, je ne montre juste plus l'erreur :-> 

A la requête suivante (1 seconde après donc) il est régénéré, et tout roule.
